import { AIService } from '../../src/services/aiService';

// Mock Supabase
jest.mock('../../src/config/supabase', () => ({
  supabase: {
    from: jest.fn().mockReturnValue({
      select: jest.fn().mockReturnThis(),
      insert: jest.fn().mockReturnThis(),
      update: jest.fn().mockReturnThis(),
      delete: jest.fn().mockReturnThis(),
      eq: jest.fn().mockReturnThis(),
      maybeSingle: jest.fn().mockResolvedValue({ data: null, error: null }),
      single: jest.fn().mockResolvedValue({ data: { id: 'mock-item-id' }, error: null }),
    }),
  },
}));

global.fetch = jest.fn() as jest.Mock;

describe('AIService Unit Tests', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('generateSummary', () => {
    it('should generate summary and tags when Gemini API returns valid JSON', async () => {
      const mockGeminiText = JSON.stringify({
        summary: 'This is a test summary generated by AI.',
        tags: ['test', 'jest'],
        category: 'Development',
        priority: 85,
      });

      const mockGeminiResponse = {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: mockGeminiText,
                },
              ],
            },
          },
        ],
      };

      (global.fetch as jest.Mock).mockImplementation(() =>
        Promise.resolve({
          ok: true,
          status: 200,
          json: () => Promise.resolve(mockGeminiResponse),
          text: () => Promise.resolve(JSON.stringify(mockGeminiResponse)),
        })
      );

      const result = await AIService.generateSummary('Test Title', 'https://example.com/article', 'generic', 'Article content snippet...');
      expect(result.summary).toBeDefined();
      expect(Array.isArray(result.tags)).toBe(true);
      expect(result.priority).toBeGreaterThan(0);
    });

    it('should fallback gracefully when Gemini API returns error or invalid response', async () => {
      (global.fetch as jest.Mock).mockResolvedValue({
        ok: false,
        status: 500,
        text: () => Promise.resolve('API Error'),
      });

      const result = await AIService.generateSummary('Test Title', 'https://example.com/article', 'generic', 'Some snippet text here.');
      expect(result.summary).toBeDefined();
      expect(result.tags.length).toBeGreaterThan(0);
      expect(result.priority).toBeGreaterThanOrEqual(10);
    });
  });

  describe('processItemEnrichment stale summary handling', () => {
    it('should use existing extracted_text without re-fetching YouTube when re-enriching item with stale summary', async () => {
      const mockRow = {
        extracted_text: 'Existing extracted transcript text of 2000 chars...',
        description: null,
        title: 'Existing Video Title',
      };

      const { supabase } = require('../../src/config/supabase');
      (supabase.from as jest.Mock).mockReturnValue({
        select: jest.fn().mockReturnThis(),
        update: jest.fn().mockReturnThis(),
        eq: jest.fn().mockReturnThis(),
        maybeSingle: jest.fn().mockResolvedValue({ data: mockRow, error: null }),
      });

      (global.fetch as jest.Mock).mockImplementation(() =>
        Promise.resolve({
          ok: true,
          status: 200,
          json: () => Promise.resolve({
            candidates: [{ content: { parts: [{ text: 'Generated summary from existing transcript.' }] } }]
          }),
          text: () => Promise.resolve(''),
        })
      );

      await AIService.processItemEnrichment('mock-item-id', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'user-id-123');

      expect(supabase.from).toHaveBeenCalledWith('items');
    });
  });

  describe('extractYouTubeContent caption extraction safety', () => {
    it('should skip fetching caption URLs containing ip=0.0.0.0 and proceed to fallback strategies', async () => {
      const videoUrl = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';

      (global.fetch as jest.Mock).mockImplementation((url: string) => {
        if (typeof url === 'string' && url.includes('youtubei/v1/player')) {
          return Promise.resolve({
            ok: true,
            status: 200,
            json: () => Promise.resolve({
              videoDetails: { title: 'Test Video Title', lengthSeconds: '212' },
              captions: {
                playerCaptionsTracklistRenderer: {
                  captionTracks: [
                    {
                      baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&ip=0.0.0.0&expire=12345',
                      languageCode: 'en',
                    },
                  ],
                },
              },
            }),
            text: () => Promise.resolve(''),
          });
        }

        if (typeof url === 'string' && url.includes('api/timedtext?v=dQw4w9WgXcQ&lang=en')) {
          return Promise.resolve({
            ok: true,
            status: 200,
            text: () => Promise.resolve('<transcript><text start="0" dur="2">Hello world from direct timedtext fallback transcript</text></transcript>'),
          });
        }

        return Promise.resolve({
          ok: false,
          status: 404,
          text: () => Promise.resolve(''),
        });
      });

      const res = await AIService.extractYouTubeContent(videoUrl);

      // Verify that fetch was never called with ip=0.0.0.0
      const fetchCalls = (global.fetch as jest.Mock).mock.calls;
      const fetchedIpUrl = fetchCalls.some(call => typeof call[0] === 'string' && call[0].includes('ip=0.0.0.0'));
      expect(fetchedIpUrl).toBe(false);

      // Verify that transcript was extracted from the fallback
      expect(res.transcript).toContain('Hello world from direct timedtext fallback transcript');
      expect(res.title).toBe('Test Video Title');
      expect(res.durationSeconds).toBe(212);
    });
  });
});

