import { AIService } from '../../src/services/aiService';
import { YouTubeExtractor } from '../../src/services/youtubeExtractor';

// Mock Supabase
jest.mock('../../src/config/supabase', () => ({
  supabase: {
    from: jest.fn().mockReturnValue({
      select: jest.fn().mockReturnThis(),
      insert: jest.fn().mockReturnThis(),
      update: jest.fn().mockReturnThis(),
      delete: jest.fn().mockReturnThis(),
      eq: jest.fn().mockReturnThis(),
      maybeSingle: jest.fn().mockResolvedValue({ data: null, error: null }),
      single: jest.fn().mockResolvedValue({ data: { id: 'mock-item-id' }, error: null }),
    }),
  },
}));

global.fetch = jest.fn() as jest.Mock;

describe('AIService Unit Tests', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('generateSummary', () => {
    it('should generate summary and tags when Gemini API returns valid JSON', async () => {
      const mockGeminiText = JSON.stringify({
        summary: 'This is a test summary generated by AI.',
        tags: ['test', 'jest'],
        category: 'Development',
        priority: 85,
      });

      const mockGeminiResponse = {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: mockGeminiText,
                },
              ],
            },
          },
        ],
      };

      (global.fetch as jest.Mock).mockImplementation(() =>
        Promise.resolve({
          ok: true,
          status: 200,
          json: () => Promise.resolve(mockGeminiResponse),
          text: () => Promise.resolve(JSON.stringify(mockGeminiResponse)),
        })
      );

      const result = await AIService.generateSummary('Test Title', 'https://example.com/article', 'generic', 'Article content snippet...');
      expect(result.summary).toBeDefined();
      expect(Array.isArray(result.tags)).toBe(true);
      expect(result.priority).toBeGreaterThan(0);
    });

    it('should fallback gracefully when Gemini API returns error or invalid response', async () => {
      (global.fetch as jest.Mock).mockResolvedValue({
        ok: false,
        status: 500,
        text: () => Promise.resolve('API Error'),
      });

      const result = await AIService.generateSummary('Test Title', 'https://example.com/article', 'generic', 'Some snippet text here.');
      expect(result.summary).toBeDefined();
      expect(result.tags.length).toBeGreaterThan(0);
      expect(result.priority).toBeGreaterThanOrEqual(10);
    });
  });

  describe('processItemEnrichment stale summary handling', () => {
    it('should use existing extracted_text without re-fetching YouTube when re-enriching item with stale summary', async () => {
      const mockRow = {
        extracted_text: 'Existing extracted transcript text of 2000 chars...',
        description: null,
        title: 'Existing Video Title',
      };

      const { supabase } = require('../../src/config/supabase');
      (supabase.from as jest.Mock).mockReturnValue({
        select: jest.fn().mockReturnThis(),
        update: jest.fn().mockReturnThis(),
        eq: jest.fn().mockReturnThis(),
        maybeSingle: jest.fn().mockResolvedValue({ data: mockRow, error: null }),
      });

      (global.fetch as jest.Mock).mockImplementation(() =>
        Promise.resolve({
          ok: true,
          status: 200,
          json: () => Promise.resolve({
            candidates: [{ content: { parts: [{ text: 'Generated summary from existing transcript.' }] } }]
          }),
          text: () => Promise.resolve(''),
        })
      );

      await AIService.processItemEnrichment('mock-item-id', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'user-id-123');

      expect(supabase.from).toHaveBeenCalledWith('items');
    });
  });

  describe('extractYouTubeContent via YouTubeExtractor', () => {
    it('should delegate extractYouTubeContent call to YouTubeExtractor', async () => {
      const videoUrl = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';
      const spy = jest.spyOn(YouTubeExtractor, 'extractYouTubeContent').mockResolvedValueOnce({
        success: true,
        videoId: 'dQw4w9WgXcQ',
        url: videoUrl,
        title: 'Mock Video Title',
        transcript: 'Mock transcript content',
        extractionMethod: 'yt-dlp',
        ytDlpVersion: '2026.08.19',
        transcriptLength: 23,
      });

      const res = await AIService.extractYouTubeContent(videoUrl);
      expect(spy).toHaveBeenCalledWith(videoUrl);
      expect(res).toBeDefined();
      expect(res.title).toBe('Mock Video Title');
      expect(res.transcript).toBe('Mock transcript content');
    });

    it('should record failure and enforce backoff for repeated invalid video extractions', async () => {
      const videoUrl = 'https://www.youtube.com/watch?v=invalid_vid_backoff_test';
      const spy = jest.spyOn(YouTubeExtractor, 'extractYouTubeContent').mockImplementation(async (url) => {
        const vid = YouTubeExtractor.extractVideoId(url)!;
        const { inBackoff } = YouTubeExtractor.isVideoInBackoff(vid);
        if (inBackoff) {
          return { success: false, videoId: vid, url, extractionMethod: 'backoff', ytDlpVersion: '2026', transcriptLength: 0, error: 'backoff' };
        }
        YouTubeExtractor.recordFailure(vid, false);
        return { success: false, videoId: vid, url, extractionMethod: 'cli', ytDlpVersion: '2026', transcriptLength: 0, error: 'failed' };
      });

      const res1 = await AIService.extractYouTubeContent(videoUrl);
      expect(res1.transcript).toBe('');

      const res2 = await AIService.extractYouTubeContent(videoUrl);
      expect(res2.transcript).toBe('');
      expect(spy).toHaveBeenCalledTimes(2);
    });
  });

});




