import { AIService } from '../../src/services/aiService';

// Mock Supabase
jest.mock('../../src/config/supabase', () => ({
  supabase: {
    from: jest.fn().mockReturnValue({
      select: jest.fn().mockReturnThis(),
      insert: jest.fn().mockReturnThis(),
      update: jest.fn().mockReturnThis(),
      delete: jest.fn().mockReturnThis(),
      eq: jest.fn().mockReturnThis(),
      maybeSingle: jest.fn().mockResolvedValue({ data: null, error: null }),
      single: jest.fn().mockResolvedValue({ data: { id: 'mock-item-id' }, error: null }),
    }),
  },
}));

global.fetch = jest.fn() as jest.Mock;

describe('AIService Unit Tests', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('generateSummary', () => {
    it('should generate summary and tags when Gemini API returns valid JSON', async () => {
      const mockGeminiText = JSON.stringify({
        summary: 'This is a test summary generated by AI.',
        tags: ['test', 'jest'],
        category: 'Development',
        priority: 85,
      });

      const mockGeminiResponse = {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: mockGeminiText,
                },
              ],
            },
          },
        ],
      };

      (global.fetch as jest.Mock).mockImplementation(() =>
        Promise.resolve({
          ok: true,
          status: 200,
          json: () => Promise.resolve(mockGeminiResponse),
          text: () => Promise.resolve(JSON.stringify(mockGeminiResponse)),
        })
      );

      const result = await AIService.generateSummary('Test Title', 'https://example.com/article', 'generic', 'Article content snippet...');
      expect(result.summary).toBeDefined();
      expect(Array.isArray(result.tags)).toBe(true);
      expect(result.priority).toBeGreaterThan(0);
    });

    it('should fallback gracefully when Gemini API returns error or invalid response', async () => {
      (global.fetch as jest.Mock).mockResolvedValue({
        ok: false,
        status: 500,
        text: () => Promise.resolve('API Error'),
      });

      const result = await AIService.generateSummary('Test Title', 'https://example.com/article', 'generic', 'Some snippet text here.');
      expect(result.summary).toBeDefined();
      expect(result.tags.length).toBeGreaterThan(0);
      expect(result.priority).toBeGreaterThanOrEqual(10);
    });
  });
});
